# Generated by Django 5.0.6 on 2025-09-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
