# Generated by Django 5.0.6 on 2025-09-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0002_interview_uploaded_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="extracted_audio",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
