# Generated by Django 5.0.6 on 2025-09-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0003_interview_extracted_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="transcript",
            field=models.TextField(blank=True, null=True),
        ),
    ]
