# Generated by Django 5.0.6 on 2025-10-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0004_interview_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="status",
            field=models.CharField(default="uploaded", max_length=50),
        ),
    ]
